.PHONY: default ../dist/tmpl/student.html ../dist/tmpl/staff.html ../dist/tmpl/login.html

default: ../dist/tmpl/student.html ../dist/tmpl/staff.html ../dist/tmpl/login.html

../dist/tmpl/student.html: student.html
	mkdir -p ../dist/tmpl
	cp student.html ../dist/tmpl/student.html

../dist/tmpl/staff.html: staff.html
	mkdir -p ../dist/tmpl
	cp staff.html ../dist/tmpl/staff.html

../dist/tmpl/login.html: login.html
	mkdir -p ../dist/tmpl
	cp login.html ../dist/tmpl/login.html
