\documentclass[parskip=half-]{scrartcl}

\subject{IBDP Computer Science Internal Assessment}
\author{Runxi Yu}
\date{\today}

\usepackage{fontspec}
\setmainfont{TeX Gyre Termes}
\setsansfont{TeX Gyre Heros}
\setmonofont{DejaVu Sans Mono}[Scale=0.86]
\usepackage{unicode-math}
\setmathfont{TeX Gyre Termes Math}
\usepackage{microtype}

\usepackage{xcolor}
\usepackage[colorlinks, allcolors={white!40!blue!50!black}]{hyperref}
