.SUFFIXES: .tex .pdf

.PHONY: all

all: appendix.pdf crita_planning.pdf critb_design.pdf critb_recordoftasks.pdf critc_development.pdf critd_functionality.pdf crite_evaluation.pdf

.tex.pdf:
	pdflatex $<
	pdflatex $<
