\input texinfo   @c -*-texinfo-*-
@comment %**start of header
@settitle Admin Handbook -- Co-curricular Activity Selection System
@syncodeindex pg cp
@comment %**end of header

@copying
This manual is written by Runxi Yu. It is hereby placed in the public domain,
under Creative Commons Zero 1.0 Universal. A copy is included in the section
entitled ``Creative Commons Zero 1.0 Universal''.
@end copying

@titlepage
@title Co-curricular Activity Selection System
@subtitle Administrator Handbook
@author Runxi Yu (@email{me@@runxiyu.org})
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@node Top
@top Co-curricular Activity Selection System

In this manual, the software is abbreviated as ``CCASS''.

@node Compiling CCASS
@chapter Compiling CCASS

Compiling CCAS is the same as compiling any other Go program. A Makefile is also provided for convenience.

@bye
